export const MEDECINLOGIN = 'MEDECINLOGIN';
export const MEDECINLOGOUT = 'MEDECINLOGOUT';
export const PATIENTLOGIN = 'PATIENTLOGIN';
export const PATIENTLOGOUT = 'PATIENTLOGOUT';
export const ADDALERT = 'ADDALERT';
export const FETCH_ALERTS = 'FETCH_ALERTS';
export const ADD_RESPONSE = 'ADD_RESPONSE';
